### ISSUE TITLE
images

### ISSUE THREAD

**Issue by jabbalaci** [KristofferStrube/FlipGame#2]
Nice. Does it work with images / photos too? That would be easier to memorize, compared to numbers. It would be nice if you added this feature. The user can drop the images in a subfolder and the program could take those images.

**Comment by KristofferStrube** [comment]
You could add a string to the Card class specifying a picture as a string instead of a number. I won't make this an out of the box solution, but it should be relatively easy to do if you want to.

**Comment by jabbalaci** [comment]
OK, but this game is usually played with pictures, not with numbers. It would be a nice addition.
